// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgDHSuoPSEdJUYtHBi-sthIpMQWCaFbAc',
    appId: '1:928328010113:web:8a6453b9d7ea49db4d4080',
    messagingSenderId: '928328010113',
    projectId: 'zoom-app-d1a21',
    authDomain: 'zoom-app-d1a21.firebaseapp.com',
    storageBucket: 'zoom-app-d1a21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6s_uXUPSbe0KdxJ9Xr-4k726my2l4nQU',
    appId: '1:928328010113:android:31d9f81b61de99cd4d4080',
    messagingSenderId: '928328010113',
    projectId: 'zoom-app-d1a21',
    storageBucket: 'zoom-app-d1a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnCbstGmH9o_r5lH-2S6c_nmZB70hLegU',
    appId: '1:928328010113:ios:24ace131e2e7278f4d4080',
    messagingSenderId: '928328010113',
    projectId: 'zoom-app-d1a21',
    storageBucket: 'zoom-app-d1a21.appspot.com',
    iosBundleId: 'com.example.zoomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnCbstGmH9o_r5lH-2S6c_nmZB70hLegU',
    appId: '1:928328010113:ios:abbc69f58f4a91e34d4080',
    messagingSenderId: '928328010113',
    projectId: 'zoom-app-d1a21',
    storageBucket: 'zoom-app-d1a21.appspot.com',
    iosBundleId: 'com.example.zoomApp.RunnerTests',
  );
}
